/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTroubleshootRouteImport } from './routes/_app.troubleshoot'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppDomainsIndexRouteImport } from './routes/_app.domains.index'
import { Route as AppJobsIdRouteImport } from './routes/_app.jobs.$id'
import { Route as AppDomainsIdRouteImport } from './routes/_app.domains.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTroubleshootRoute = AppTroubleshootRouteImport.update({
  id: '/troubleshoot',
  path: '/troubleshoot',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDomainsRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppDomainsIdRoute = AppDomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDomainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/domains': typeof AppDomainsRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/troubleshoot': typeof AppTroubleshootRoute
  '/domains/$id': typeof AppDomainsIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/domains/': typeof AppDomainsIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/troubleshoot': typeof AppTroubleshootRoute
  '/': typeof AppIndexRoute
  '/domains/$id': typeof AppDomainsIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/domains': typeof AppDomainsIndexRoute
  '/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_app/domains': typeof AppDomainsRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/troubleshoot': typeof AppTroubleshootRoute
  '/_app/': typeof AppIndexRoute
  '/_app/domains/$id': typeof AppDomainsIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/domains/': typeof AppDomainsIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/signup'
    | '/domains'
    | '/jobs'
    | '/servers'
    | '/settings'
    | '/troubleshoot'
    | '/domains/$id'
    | '/jobs/$id'
    | '/domains/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/auth'
    | '/signup'
    | '/servers'
    | '/settings'
    | '/troubleshoot'
    | '/'
    | '/domains/$id'
    | '/jobs/$id'
    | '/domains'
    | '/jobs'
  id:
    | '__root__'
    | '/_app'
    | '/account'
    | '/auth'
    | '/signup'
    | '/_app/domains'
    | '/_app/jobs'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/troubleshoot'
    | '/_app/'
    | '/_app/domains/$id'
    | '/_app/jobs/$id'
    | '/_app/domains/'
    | '/_app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/troubleshoot': {
      id: '/_app/troubleshoot'
      path: '/troubleshoot'
      fullPath: '/troubleshoot'
      preLoaderRoute: typeof AppTroubleshootRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/domains/': {
      id: '/_app/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppDomainsRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/domains/$id': {
      id: '/_app/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof AppDomainsIdRouteImport
      parentRoute: typeof AppDomainsRoute
    }
  }
}

interface AppDomainsRouteChildren {
  AppDomainsIdRoute: typeof AppDomainsIdRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
}

const AppDomainsRouteChildren: AppDomainsRouteChildren = {
  AppDomainsIdRoute: AppDomainsIdRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
}

const AppDomainsRouteWithChildren = AppDomainsRoute._addFileChildren(
  AppDomainsRouteChildren,
)

interface AppJobsRouteChildren {
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsIdRoute: AppJobsIdRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteChildren {
  AppDomainsRoute: typeof AppDomainsRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTroubleshootRoute: typeof AppTroubleshootRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDomainsRoute: AppDomainsRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTroubleshootRoute: AppTroubleshootRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
